# Generated by Django 4.2.28 on 2026-03-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente20898',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(default='Habitacional', max_length=100)),
                ('superficie_existente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_regularizar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anio_construccion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('ingresado', 'Ingresado DOM'), ('observado', 'Con observaciones'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proyecto')),
            ],
        ),
    ]
